### PR TITLE
Add ghc-8.10.2 to list of versions

### PR DESCRIPTION
**Pull request by bubba**

### CODE REVIEW

**Comment by asr** [comment]
I couldn't use GHC 8.10.2. I hope this PR fix the problem.

Blocking https://github.com/agda/agda/issues/4837.

**Comment by bubba** [comment]
@asr for what it's worth, you can use this branch in your workflow if you specify `bubba/setup-haskell@2215b2c`

**Comment by domenkozar** [comment]
Hope this gets merged soon!

**Comment by domenkozar** [comment]
cc @andymckay @patrickt

**Comment by andreasabel** [comment]
Ah, yes, please merge.

**Comment by andreasabel** [comment]
Thanks @patrickt!

**Pull request merged**
